# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test_ruby_version:
    runs-on: ubuntu-latest
    name: ruby-${{ matrix.ruby }}, ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        gemfile:
          - "faraday_1.x"
          - "faraday_2.x"
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Configure bundler
      run: |
        bundle config path vendor/bundle
    - name: Create bundler lockfile
      run: |
        bundle lock
    - uses: actions/cache@v3
      with:
        # NOTE: Bundler expands the path relative to the gemfile, not the
        # current directory.
        path: ./gemfiles/vendor/bundle
        key: bundled-gems-${{ runner.os }}-ruby-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles( 'gemfiles/*.lock' ) }}
        restore-keys: |
          bundled-gems-${{ runner.os }}-ruby-${{ matrix.ruby }}-${{ matrix.gemfile }}-
          bundled-gems-${{ runner.os }}-ruby-${{ matrix.ruby }}-
    - name: Install gems
      run: |
        bundle install --jobs 4
    - name: Run tests
      run: bundle exec rake
